---
output:
  html_document: default
  pdf_document: default
---
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
factors_genes = read.csv("~/Documents/mskcc/milo_gene_loadings.csv", header = FALSE) %>%
                  t() %>%
                  as.data.frame()

factors_cells = read.csv("~/Documents/mskcc/milo_cell_scores.csv", header = FALSE)

factor_names = 1:80
```

```{r}
colnames(factors_genes) <- factor_names
colnames(factors_cells) <- factor_names

factors_cells_tidy <- gather(factors_cells, "factor", "cell_score", factor_names, convert = TRUE)
factors_genes_tidy <- gather(factors_genes, "factor", "gene_loading", factor_names, convert = TRUE)
```

```{r}
factors_cells_stats <- data.frame(factor = factor_names)
factors_cells_stats$variance <- with(factors_cells_tidy, tapply(cell_score, factor, var))
factors_cells_stats$mean <- with(factors_cells_tidy, tapply(cell_score, factor, mean))

factors_genes_stats <- data.frame(factor = factor_names)
factors_genes_stats$variance <- with(factors_genes_tidy, tapply(gene_loading, factor, var))
factors_genes_stats$mean <- with(factors_genes_tidy, tapply(gene_loading, factor, mean))
factors_genes_stats$sd <- with(factors_genes_tidy, tapply(gene_loading, factor, sd))
factors_genes_stats$cutoff <- 3 * factors_genes_stats$mean + 1.5 * factors_genes_stats$sd
factors_genes_stats$important_gene_count <- sapply(factor_names, function(curr_factor) {
  subset(factors_genes_tidy, factor == curr_factor & 
         gene_loading >= factors_genes_stats$cutoff[curr_factor]) %>%
    nrow()
})
```

```{r eval=FALSE, include=FALSE}
for (curr_factor in 1:80) {
  print(factors_genes_tidy %>%
    subset(factor == curr_factor) %>%
    ggplot(aes(x = 0, y = gene_loading)) +
    geom_jitter(alpha = 0.6, width = 0.2) +
    geom_hline(aes(yintercept = factors_genes_stats$cutoff[curr_factor])) +
    labs(x = "") +
    theme_bw())
}
```

```{r}
factors_genes_tidy_cut <- data.frame(factor = factors_genes_tidy$factor)

factors_genes_tidy_cut$gene_loading <- mapply(function(curr_factor, gene_loading) {
  ifelse(gene_loading >= factors_genes_stats$cutoff[curr_factor], gene_loading, NA)
}, factors_genes_tidy$factor, factors_genes_tidy$gene_loading)

factors_genes_tidy_cut <- na.omit(factors_genes_tidy_cut)
```

```{r}
ggplot(factors_genes_tidy_cut, aes(x = factor, y = gene_loading)) +
  geom_point(alpha = 0.5) +
  labs(x = "Factor", y = "Gene Loading") +
  theme_bw()
```

```{r}
factors_genes_stats_cut <- data.frame(factor = factor_names)
factors_genes_stats_cut$variance <- with(factors_genes_tidy_cut, tapply(gene_loading, factor, var))
factors_genes_stats_cut$mean <- with(factors_genes_tidy_cut, tapply(gene_loading, factor, mean))
```

```{r}
ggplot(factors_genes_stats_cut, mapping=aes(x=factor, y=variance)) +
  geom_point() +
  labs(x = "Factor", y = "Variance of Gene Loadings") +
  theme_bw()

ggplot(factors_genes_stats_cut, mapping=aes(x=factor, y=mean)) +
  geom_point() +
  labs(x = "Factor", y = "Mean Gene Loading") +
  theme_bw()

ggplot(factors_genes_stats_cut, mapping=aes(x=mean, y=variance)) +
  geom_point() +
  labs(x = "Mean Gene Loading", y = "Variance of Gene Loadings") +
  theme_bw()
```
